db:
  image: postgres
web:
  build: .
  command: gunicorn photoz.wsgi -b 0.0.0.0:8000
  environment:
    AWS_STORAGE_BUCKET_NAME: bucket_name
    AWS_ACCESS_KEY_ID: key_id
    AWS_SECRET_ACCESS_KEY: secret_access_key
  volumes:
    - .:/usr/src/app
  ports:
    - "8000:8000"
  links:
    - db
